# Generated by Django 2.2.2 on 2019-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventapp',
            options={'verbose_name_plural': 'Event App'},
        ),
        migrations.AddField(
            model_name='eventapp',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
