# Generated by Django 2.2.2 on 2019-06-16 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_auto_20190614_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAppPolling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('selectedDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Event App Polling',
            },
        ),
    ]
