# Generated by Django 2.2.2 on 2019-06-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_eventapppolling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventapppolling',
            old_name='selectedDate',
            new_name='datePicker',
        ),
        migrations.RenameField(
            model_name='eventapppolling',
            old_name='name',
            new_name='inputname',
        ),
    ]
