# Generated by Django 2.2.2 on 2019-06-17 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_auto_20190616_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapppolling',
            name='eventName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventapppolling',
            name='datePicker',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
